{
    "id": "wrong_mix_domain_foundationPlace_00020_1",
    "rank": 37,
    "data": {
        "url": "https://forums.insynchq.com/t/you-cannot-add-google-drive-name-to-the-root-of-the-shared-drives/18283",
        "read_more_link": "",
        "language": "en",
        "title": "\"You cannot add (Google Drive name) to the root of the Shared drives\"",
        "top_image": "https://forums.insynchq.com/uploads/default/original/2X/3/3857e627b8a20f7ea1e1c18c05452fe854333504.png",
        "meta_img": "https://forums.insynchq.com/uploads/default/original/2X/3/3857e627b8a20f7ea1e1c18c05452fe854333504.png",
        "images": [
            "https://forums.insynchq.com/uploads/default/original/2X/5/512177671bb165659089bbcbe807f99a9caffde1.png"
        ],
        "movies": [],
        "keywords": [],
        "meta_keywords": [
            ""
        ],
        "tags": null,
        "authors": [
            "mia closed"
        ],
        "publish_date": "2022-04-17T02:10:32+00:00",
        "summary": "",
        "meta_description": "“You cannot add Google Drive name to the root of the Shared drives, as this is not allowed by Google Drive. To remove this error, move (Google Drive name) out of the root location” \nI couldn’t upload files (no download) &hellip;",
        "meta_lang": "en",
        "meta_favicon": "https://forums.insynchq.com/uploads/default/optimized/1X/6db254671c6d104b61efaa0182ac3120c28767f6_2_32x32.ico",
        "meta_site_name": "Insync Forums ❤",
        "canonical_link": "https://forums.insynchq.com/t/you-cannot-add-google-drive-name-to-the-root-of-the-shared-drives/18283",
        "text": "“You cannot add Google Drive name to the root of the Shared drives, as this is not allowed by Google Drive. To remove this error, move (Google Drive name) out of the root location”\n\nI couldn’t upload files (no download) to the shared drive until now, and when I did, I tried uploading a folder with two sub-directories in it. However, it not only didn’t upload the main folder, but it only (tried and failed) uploaded the sub-directories, and then this error was thrown. Now that shared drive doesn’t show again.\n\nThis is odd because a drive shared with me by a friend I can upload (1-way-sync) to it. Is it because I’m the owner of this shared drive?\n\nHi! This means that you cannot add a file/folder to the root of a Shared Drive folder from local to cloud; it needs to be uploaded within an existing Shared Drive folder.\n\nI would suggest creating a new folder via Shared Drive web first, then you can upload these local folders to that directory. Let me know if the issue persists.\n\nI’m not sure if this affecting it, however, it keeps telling me “the base folder located at {location} is missing. Please locate the base folder to continue syncing.” I’ve changed the base folder, but it doesn’t seem to be changing it completely and it is stuck at that location.\n\nEdit: Well, after re-creating the folders for Insync to recognize, I had to unsync it for it to stop throwing errors and that, unfortunately, caused Insync to delete everything from my Google Drive.\n\nHi @Firon,\n\nMy apologies for the trouble you experienced. Recreating the location with an empty folder will indeed lead to a cloud deletion since Insync registers that empty folder as the user removing all the contents from the local folder. From what I’m understanding however, you recreated the folders the way they were, contents and all?\n\nIt’s interesting you mentioned that unsyncing led to a deletion. Did you mean that it removed your files from the local Google Drive (which is the expected outcome) or were the files deleted from the cloud as well?\n\nMoving forward, if you experience a base folder is missing error, it’s best to remove the account and re-add it afterwards.\n\nTo sum up and highlight the answer to your questions:\n\nFrom what I’m understanding however, you recreated the folders the way they were, contents and all?\n\nI only created the main folder and not sub-directories.\n\nDid you mean that it removed your files from the local Google Drive (which is the expected outcome) or were the files deleted from the cloud as well?\n\nIt deleted it locally and in the cloud.\n\nI only created the main folder and not sub-directories. However, for that specific folder, I wanted only one-way syncing (Local to Cloud) I didn’t want to download from the cloud. That same folder is the one mentioned in this original post. I’m not sure why it would delete the files from the cloud if it’s only uploading to the cloud and not downloading.\n\nAlso, I only had a certain folder/files in there, which also confuses me on why it would delete other files it has no associations with.\n\nHonestly, the program itself looks wonderful and can be great, however, issues like this (big and small), are making me want to switch back to a previous program I was using. At least until a lot of these bugs are ironed out. I hope these issues can be dealt with before any new features. Just my two cents.\n\nThank you for that suggestion, I will keep that in mind. However as I stated previously, these are poor solutions and should not have to be a problem in the first place to be dealt with.\n\nEdit: After logging out and back in, I still get the error that the base folder is missing.\n\nEdit 2: When trying to one-way sync a folder/zip to the cloud, it just makes the shared drive disappear. However, the other shared drive I have does not disappear, but it does not allow me to upload It to that one either.\n\nEdit 3: Trying to two-way sync a folder I created on Google Drive (2-way sync) threw some type of error and outputted the error below to the log:\n\nC:\\Users\\Firon\\AppData\\Roaming\\Insync\\App\\ideskui\\appui.py:599: RuntimeWarning: coroutine ‘APIFunction.call’ was never awaited\n\nRuntimeWarning: Enable tracemalloc to get the object allocation traceback\n\nPython WNDPROC handler failed\n\nTraceback (most recent call last):\n\nFile “ideskwin\\htmlui_impl.py”, line 357, in __OnClose\n\nFile “ideskui\\htmlui.py”, line 76, in hide\n\nFile “ideskwin\\htmlui_impl.py”, line 54, in hide\n\nFile “ideskui\\appui.py”, line 599, in on_hide\n\nFile “ideskasync\\coreloop.py”, line 131, in wrapper\n\nFile “ideskasync\\coreloop.py”, line 45, in run\n\nFile “asyncio\\tasks.py”, line 813, in run_coroutine_threadsafe\n\nAttributeError: ‘NoneType’ object has no attribute ‘call_soon_threadsafe’\n\nI’ve tried reinstalling.\n\nHello @Firon! Do you mind sending the following to support@insynchq.com with the link to this post:\n\nlogs.db\n\nout.txt\n\n“data” folder\n\n“live” folder\n\nfile path of the missing base folder (screenshot will do)\n\nname of local folder you tried to 1-way sync and which cloud folder you wanted to sync it to\n\nname of folder you tried to 2-way sync that threw the error\n\nThe first 4 items above should be in %AppData%\\Insync on your machine. Thank you!\n\nI got the same issue as the second part:\n\nError: “The base folder located at {location} is missing. Please locate the base folder to continue syncing.\"\n\nThen there are red crosses in front of some of my folders. I could identify that all concerned folders are shared from my first Google account, and have been added to the root of my second account’s drive as true folders, at the time where Google allowed us to do that (it was fully supported, then only available via Ctrl+Z, then unsupported and only symlinks are now allowed).\n\nMy hypothesis is that after Google’s change, insync doesn’t support detecting old-style true folder sharing and will stop updating such folders, only permitting symlinks. Note that unlike the OP, everything is located in the original root folder, not the default Shared folder.\n\nFor some reason, the error only shows on Windows though. Maybe because I haven’t been there for a while and it has trouble identifying every folder? (that said said folders have been there for a while too, my Windows session should know at least the oldest ones)\n\nOn Linux, insync keeps syncing things as normal.\n\nIt seems that changes in these folders are ignored from both sides, the folder sync has completely stopped. I may have to completely switch to the new Shared folders system. Problem is, all these folders already added are not visible in Shared with me in addition, I’d have to remove them from root sharing first; and if I do this, back on Linux, I will have all my existing and working folders removed, and I’ll have to resync them locally to some custom shared folder location…"
    }
}